export const STORE_USER_INFO="STORE_USER_INFO";
export const SUBMIT_ORDER="SUBMIT_ORDER";
export const VALIDATE_ADDRESS_START="VALIDATE_ADDRESS_START";
export const VALIDATE_ADDRESS_SUCCESS="VALIDATE_ADDRESS_SUCCESS";
export const VALIDATE_ADDRESS_FAILED="VALIDATE_ADDRESS_FAILED";
export const VALIDATE_ADDRESS_RESET="VALIDATE_ADDRESS_RESET";