export const SUBMIT_ORDER_START = 'SUBMIT_ORDER_START';
export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER_SUCCESS';
export const SUBMIT_ORDER_FAILED = 'SUBMIT_ORDER_FAILED';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_START = 'GET_ORDERS_START';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED';
export const CLEAR_DELIVERY_ADDRESS = 'CLEAR_DELIVERY_ADDRESS';
export const VALIDATE_DELIVERY_ADDRESS_START =
  'VALIDATE_DELIVERY_ADDRESS_START';
export const VALIDATE_DELIVERY_ADDRESS_SUCCESS =
  'VALIDATE_DELIVERY_ADDRESS_SUCCESS';
export const VALIDATE_DELIVERY_ADDRESS_FAILED =
  'VALIDATE_DELIVERY_ADDRESS_FAILED';
export const VALIDATE_DELIVERY_ADDRESS_RESET =
  'VALIDATE_DELIVERY_ADDRESS_RESET';
export const SET_ERRORED_ACTION = 'SET_ERRORED_ACTION';
