export const CRUST = "crust";
export const SIZE = "size";
export const SAUCE = "sauce";
export const SAUCE_AMOUNT = "sauceAmount";
export const CHEESE_AMOUNT = "cheeseAmount";
export const CRUST_FLAVOR = "crustFlavor";
export const MEATS = "meats";
export const VEGGIES = "veggies";
export const COMBO_NAME="comboName"