export const INIT_PIZZA_BUILDER = 'INIT_PIZZA_BUILDER';
export const CLOSE_PIZZA_BUILDER = 'CLOSE_PIZZA_BUILDER';
export const SET_PROPERTY = 'SET_PROPERTY';
export const TOGGLE_TOPPING = 'TOGGLE_TOPPING';
export const SET_TOPPING_AMOUNT = 'SET_TOPPING_AMOUNT';
export const SET_TOPPING_PORTION = 'SET_TOPPING_PORTION';
