export const INIT_PIZZA_BUILDER = "INIT_PIZZA_BUILDER";
export const CLOSE_PIZZA_BUILDER = "CLOSE_PIZZA_BUILDER";
export const SET_PROPERTY = "SET_PROPERTY";
export const TOGGLE_TOPPING = "TOGGLE_TOPPING";